# Generated by Django 4.2.5 on 2023-09-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_serie', models.CharField(max_length=200)),
                ('ano_lancamento', models.DateField()),
                ('quantidade_cartoes', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tiragem', models.IntegerField(max_length=10)),
                ('ordem', models.IntegerField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Series.series')),
            ],
        ),
    ]
